version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: human_monument_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: monument_user
      POSTGRES_PASSWORD: monument_pass_dev_only
      POSTGRES_DB: human_monument
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monument_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: human_monument_api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://monument_user:monument_pass_dev_only@postgres:5432/human_monument
      PORT: 5000
      CORS_ORIGIN: http://localhost:5173
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: human_monument_web
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:5000/api
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  default:
    name: human_monument_network